module.exports = {
  mySidebar: [
    'introduction',
    {
      type: 'category',
      label: 'RKE Kubernetes Installation',
      link: {type: 'doc', id: 'installation/installation',},
      items: ['installation/certs/certs'],
    },
    {
      type: 'category',
      label: 'Upgrades',
      link: {type: 'doc', id: 'upgrades/upgrades',},
      items:[
          'upgrades/how-upgrades-work/how-upgrades-work',
          'upgrades/maintaining-availability/maintaining-availability',
          'upgrades/configuring-strategy/configuring-strategy',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'kubeconfig',
    },
    {
      type: 'category',
      label: 'Backups and Disaster Recovery',
      link: {type: 'doc', id: 'etcd-snapshots/etcd-snapshots',},
      items:[
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/one-time-snapshots',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/recurring-snapshots',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/restoring-from-backup',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/example-scenarios',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/troubleshooting',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'cert-mgmt',
    },
    {
      type: 'autogenerated',
      dirName: 'managing-clusters',
    },
    {
      type: 'category',
      label: 'Kubernetes Configuration Options',
      link: {type: 'doc', id: 'config-options/config-options',},
      items:[
        'config-options/nodes/nodes',
        'config-options/private-registries/private-registries',
        'config-options/bastion-host/bastion-host',
        'config-options/system-images/system-images',

        {
          type: 'autogenerated',
          dirName: 'config-options/services',
        },
        'config-options/secrets-encryption/secrets-encryption',
        'config-options/authentication/authentication',
        'config-options/authorization/authorization',
        'config-options/rate-limiting/rate-limiting',

        {
          type: 'autogenerated',
          dirName: 'config-options/cloud-providers',
        },
        'config-options/audit-log/audit-log',
        'config-options/dual-stack/dual-stack',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'example-yamls',
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {type: 'doc', id: 'troubleshooting/troubleshooting',},
      items:[
        {
          type: 'autogenerated',
          dirName: 'troubleshooting/ssh-connectivity-errors',
        },
        {
          type: 'autogenerated',
          dirName: 'troubleshooting/provisioning-errors',
        },
      ],
    },
  ],
};