module.exports = {
  mySidebar: [
    'introduction',
    {
      type: 'category',
      label: 'RKE Kubernetes Installation',
      link: {type: 'doc', id: 'installation/installation_index',},
      items: ['installation/certs/installation_certs_index'],
    },
    {
      type: 'category',
      label: 'Upgrades',
      link: {type: 'doc', id: 'upgrades/upgrades_index',},
      items:[
          'upgrades/how-upgrades-work/how-upgrades-work_index',
          'upgrades/maintaining-availability/maintaining-availability_index',
          'upgrades/configuring-strategy/configuring-strategy_index',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'kubeconfig',
    },
    {
      type: 'category',
      label: 'Backups and Disaster Recovery',
      link: {type: 'doc', id: 'etcd-snapshots/etcd-snapshots_index',},
      items:[
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/one-time-snapshots',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/recurring-snapshots',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/restoring-from-backup',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/example-scenarios',
        },
        {
          type: 'autogenerated',
          dirName: 'etcd-snapshots/troubleshooting',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'cert-mgmt',
    },
    {
      type: 'autogenerated',
      dirName: 'managing-clusters',
    },
    {
      type: 'category',
      label: 'Kubernetes Configuration Options',
      link: {type: 'doc', id: 'config-options/config-options_index',},
      items:[
        'config-options/nodes/nodes_index',
        'config-options/private-registries/private-registries_index',
        'config-options/bastion-host/bastion-host_index',
        'config-options/system-images/system-images_index',

        {
          type: 'autogenerated',
          dirName: 'config-options/services',
        },
        'config-options/secrets-encryption/secrets-encryption_index',
        'config-options/authentication/authentication_index',
        'config-options/authorization/authorization_index',
        'config-options/rate-limiting/rate-limiting_index',

        {
          type: 'autogenerated',
          dirName: 'config-options/cloud-providers',
        },
        'config-options/audit-log/audit-log_index',
        'config-options/dual-stack/dual-stack_index',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'example-yamls',
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {type: 'doc', id: 'troubleshooting/troubleshooting_index',},
      items:[
        {
          type: 'autogenerated',
          dirName: 'troubleshooting/ssh-connectivity-errors',
        },
        {
          type: 'autogenerated',
          dirName: 'troubleshooting/provisioning-errors',
        },
      ],
    },
  ],
};